### ISSUE TITLE
Exception UnboundLocalError: local variable 'sock' referenced before assignment

### ISSUE THREAD

**Issue by stuertz** [StephanJoubert/home_assistant_solarman#214]
```
2023-02-11 17:10:32.485 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.solarman_nord_running_status fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 548, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/solarman/sensor.py", line 140, in update
    self.inverter.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/solarman/solarman.py", line 175, in update
    self.get_statistics()
  File "/config/custom_components/solarman/solarman.py", line 234, in get_statistics
    finally:
UnboundLocalError: local variable 'sock' referenced before assignment
```

**Comment by stuertz** [comment]
Already fixed with 4dcaa7762184ef2f13cc6089b15ba88e8e3c602a
