### ISSUE TITLE
DEYE -SG04LP3-EU How to connect

### ISSUE THREAD

**Issue by MarmaGoms** [StephanJoubert/home_assistant_solarman#314]
Just got new hybrid inverter and try to connect.
Already using Solarman Smart mobile app which is working fine.
From the router I see the IP of the inverter, but it does not response http (not open in browser, does not even ask login). Is this because app in use? How to reset logger / disconnect the app, if that is the reason?
HA show 55 entities, all unavailable.

HA gives following log:
WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration solarman which has not been tested by Home Assistant.
...
WARNING (SyncWorker_3) [custom_components.solarman.solarman] Querying inverter 27xxxxxxxx at 192.168.xx.xxx:8899 failed on connection start with exception [OSError]
DEBUG (MainThread) [custom_components.solarman.config_flow] config_flow.py:ConfigFlow.async_get_options_flow: <homeassistant.config_entries.ConfigEntry object at 0x7f9f9524d0>
DEBUG (MainThread) [custom_components.solarman.config_flow] config_flow.py:OptionsFlow.__init__: <homeassistant.config_entries.ConfigEntry object at 0x7f9f9524d0>
DEBUG (MainThread) [custom_components.solarman.config_flow] config_flow.py:OptionsFlow.async_step_init: None
DEBUG (MainThread) [custom_components.solarman.config_flow] config_flow.py:step_user_data_schema: {'name': 'DEYE', 'inverter_host': '192.168.xx.xxx', 'inverter_serial': 27xxxxxxxx, 'inverter_port': 8899, 'inverter_mb_slaveid': 1, 'lookup_file': 'deye_sg04lp3.yaml'}
DEBUG (MainThread) [custom_components.solarman.config_flow] config_flow.py:step_user_data_schema: STEP_USER_DATA_SCHEMA: {'name': <class 'str'>, 'inverter_host': <class 'str'>, 'inverter_serial': <class 'int'>, 'inverter_port': <class 'int'>, 'inverter_mb_slaveid': <class 'int'>, 'lookup_file': In(['deye_4mppt.yaml', 'deye_hybrid.yaml', 'deye_sg04lp3.yaml', 'deye_string.yaml', 'sofar_lsw3.yaml', 'sofar_wifikit.yaml', 'solis_hybrid.yaml', 'solis_1p8k-5g.yaml', 'sofar_g3hyd.yaml', 'sofar_hyd3k-6k-es.yaml', 'zcs_azzurro-ktl-v3.yaml', 'custom_parameters.yaml'])}
DEBUG (MainThread) [custom_components.solarman.config_flow] config_flow.py:OptionsFlow.async_step_init: {'name': 'DEYE', 'inverter_host': '192.168.xx.xxx', 'inverter_serial': 27xxxxxxxx, 'inverter_port': 8899, 'inverter_mb_slaveid': 1, 'lookup_file': 'deye_sg04lp3.yaml'}
DEBUG (MainThread) [custom_components.solarman.config_flow] config_flow.py:validate_input: {'name': 'DEYE', 'inverter_host': '192.168.xx.xxx', 'inverter_serial': 27xxxxxxxx, 'inverter_port': 8899, 'inverter_mb_slaveid': 1, 'lookup_file': 'deye_sg04lp3.yaml'}
DEBUG (SyncWorker_5) [custom_components.solarman.solarman] Starting to query for [6] ranges...
WARNING (SyncWorker_5) [custom_components.solarman.solarman] Querying inverter 27xxxxxxxx at 192.168.xx.xxx:8899 failed on connection start with exception [OSError]
ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.xx.xxx for solarman
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 543, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/solarman/__init__.py", line 28, in async_unload_entry
    hass.data[DOMAIN].pop(entry.entry_id)
KeyError: 'solarman'

**Comment by MarmaGoms** [comment]
This was a local network configuration issue, please ignore.
