### ISSUE TITLE
Reboot - error, unknown state until next reboot.

### ISSUE THREAD

**Issue by JDTm** [StephanJoubert/home_assistant_solarman#355]
Hi,
am using haOS (2023.7.2), Solarman v1.4.3 and a deye SUN600G3. 
When i reboot my homeassistant when the inverter is offline (no sun (ie in the night)) it will not come back until i reboot again, when its online.

2023-07-18 23:36:24.576 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up solarman platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/solarman/sensor.py", line 79, in async_setup_entry
_do_setup_platform(hass, entry.options, async_add_entities)
File "/config/custom_components/solarman/sensor.py", line 49, in _do_setup_platform
raise vol.Invalid('configuration parameter [inverter_serial] does not have a value')
voluptuous.error.Invalid: configuration parameter [inverter_serial] does not have a value

**Comment by raspitoaster** [comment]
Same issue here.
When I reboot or even just restart the Homeassistant when the inverter is offline at night, the Solarman integration does not properly connect to the inverter when the inverter comes back in the morning.
I have to restart Homeassistant again when the inverter is online and then everything is fine.
