### ISSUE TITLE
Not working in HA 2024.02

### ISSUE THREAD

**Issue by felipebraz** [StephanJoubert/home_assistant_solarman#512]
I receive the error: Querying [1 - 125] failed with exception [OSError: [Errno 30] Read-only file system]

HA Version:
- Core: 2024.2.0
- Front-end: 20240207.0

Integration Version: 1.5.1

Model: deye_4mppt

**Comment by sdhein** [comment]
> I receive the error: Querying [1 - 125] failed with exception [OSError: [Errno 30] Read-only file system]
> 
> HA Version:
> 
> * Core: 2024.2.0
> * Front-end: 20240207.0
> 
> Integration Version: 1.5.1
> 
> Model: deye_4mppt

Also failing for me.

**Comment by Runortyx** [comment]
Same Problem here, freshly pulled the addon.

If i want do use the workflow:
![grafik](https://github.com/StephanJoubert/home_assistant_solarman/assets/14290830/629a512e-fcd4-4d5a-93c5-b3d397956958)

If i configured manually:
`

Logger: homeassistant.config
Source: config.py:1518
First occurred: 09:58:29 (1 occurrences)
Last logged: 09:58:29
Platform error: sensor - Exception importing custom_components.solarman.sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 847, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 864, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/solarman/__init__.py", line 9, in <module>
    from .const import *
  File "/config/custom_components/solarman/const.py", line 9, in <module>
    LOOKUP_FILES = (os.listdir(os.path.dirname(__file__) + '/inverter_definitions'))
                    ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1518, in async_process_component_config
    platform = p_integration.get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 856, in get_platform
    raise ImportError(
ImportError: Exception importing custom_components.solarman.sensor

`

**Comment by RichieGKB** [comment]
As with the newest HomeAssistant 24.2 update a new Python version 3.12 was shipped as well, I assume the error might be related to this.

**Comment by felipebraz** [comment]
I made something a little insane but worked for me... I run a full backup, reinstalled my HA in the latest version, restored the backup and it's working so far.
Don't know why or how, but it is... LoL

**Comment by RaeesD** [comment]
I had this problem too, fixed by downgrading docker to 24.0.9 as suggested [here](https://github.com/StephanJoubert/home_assistant_solarman/issues/499)

**Comment by theyo-tester** [comment]
Just FYI: A `ha core rebuild` would also fix this issue, as suggested later in the same thread mentioned by @RaeesD [here](https://github.com/StephanJoubert/home_assistant_solarman/issues/499#issuecomment-2050970474)

So it is more clean and you don't have to mess around with downgrading anything👍

**Comment by RaeesD** [comment]
I would also add that the [Deye/Sunsynk add-on](https://github.com/kellerza/sunsynk) supports the Solarman dongle, I've migrated to that a few months ago and enjoying up to 10s polling intervals for certain registers. Just use the dev build for now to address intermittent disconnection issues.
