### ISSUE TITLE
After HACS UPgrade Solarman stop working !

### ISSUE THREAD

**Issue by Tom-12345678** [StephanJoubert/home_assistant_solarman#653]
After HACS UPgrade Solarman stop working !

2024-09-06 15:06:46.287 INFO (MainThread) [homeassistant.components.sensor] Setting up solarman.sensor
2024-09-06 15:06:46.304 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/solarman/inverter_definitions/deye_2mppt.yaml',) inside the event loop by custom integration 'solarman' at custom_components/solarman/solarman.py, line 33: with open(self.path + self.lookup_file) as f: (offender: /config/custom_components/solarman/solarman.py, line 33: with open(self.path + self.lookup_file) as f:), please create a bug report at https://github.com/StephanJoubert/home_assistant_solarman/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
await self.async_setup(hass, integration=integration)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/solarman/__init__.py", line 18, in async_setup_entry
await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2121, in async_forward_entry_setups
await self._async_forward_entry_setups_locked(entry, platforms)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2132, in _async_forward_entry_setups_locked
await asyncio.gather(
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2134, in <genexpr>
create_eager_task(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
return Task(coro, loop=loop, name=name, eager_start=True)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2214, in _async_forward_entry_setup
await entry.async_setup(self.hass, integration=integration)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
result = await component.async_setup_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 130, in async_setup_entry
return await component.async_setup_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 194, in async_setup_entry
return await self._platforms[key].async_setup_entry(config_entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 328, in async_setup_entry
return await self._async_setup_platform(async_create_setup_awaitable)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 358, in _async_setup_platform
awaitable = create_eager_task(awaitable, loop=hass.loop)
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
return Task(coro, loop=loop, name=name, eager_start=True)
File "/config/custom_components/solarman/sensor.py", line 79, in async_setup_entry
_do_setup_platform(hass, entry.options, async_add_entities)
File "/config/custom_components/solarman/sensor.py", line 51, in _do_setup_platform
inverter = Inverter(path, inverter_sn, inverter_host, inverter_port, inverter_mb_slaveid, lookup_file)
File "/config/custom_components/solarman/solarman.py", line 33, in __init__
with open(self.path + self.lookup_file) as f:
2024-09-06 15:06:46.354 DEBUG (MainThread) [homeassistant.setup] Phase config_entry_setup for solarman (f40ff68b147060f5d5a58953926e8384) took 0.07s (elapsed=9.95s) (wait_time=9.88s)
2024-09-06 15:06:46.355 DEBUG (MainThread) [homeassistant.setup] Adding wait for wait_import_platforms for solarman (0a57cfb26fc52e2d7f680b10dfefbc0d) of 9.95
2024-09-06 15:06:46.355 INFO (MainThread) [homeassistant.components.sensor] Setting up solarman.sensor
2024-09-06 15:06:46.410 DEBUG (MainThread) [homeassistant.setup] Phase config_entry_setup for solarman (0a57cfb26fc52e2d7f680b10dfefbc0d) took 0.06s (elapsed=10.00s) (wait_time=9.95s)
2024-09-06 15:06:46.411 DEBUG (MainThread) [homeassistant.setup] Adding wait for wait_import_platforms for proximity (9509b0363bb3a7a6df5a37267ebafb82) of 10.00

**Comment by davidrapan** [comment]
Hi @Tom-12345678, I would like to suggest you to try this integration: [davidrapan/ha-solarman](https://github.com/davidrapan/ha-solarman) and see if it won't solve your issue! 😉
