### ISSUE TITLE
Error while processing event 

### ISSUE THREAD

**Issue by stamatakisa** [StephanJoubert/home_assistant_solarman#672]
Error while processing event <Event state_changed[L]: entity_id=device_tracker.2783636116, old_state=None, new_state=<state device_tracker.2783636116=home; source_type=router, ip=192.168.88.29, mac=***********, host_name=2783636116, attribution=Data provided by Mikrotik, interface=bridge, source=dhcp, last_seen=Now, icon=mdi:lan-connect, friendly_name=inverter_deye @ 2024-10-06T15:28:57.520829+03:00>> for domain device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 608, in _async_dispatch_domain_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 937, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 377, in _async_process_device_event
    self._async_process_device_state(event.data["new_state"])
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 397, in _async_process_device_state
    self.async_process_client(ip_address, hostname, mac_address)
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 234, in async_process_client
    and data[HOSTNAME].startswith(hostname)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'startswith'

**Comment by stamatakisa** [comment]
i have this issue every time and i dont know what i do
